- hosts: all
  vars:
  tasks:
    - name: 2.1.1 Ensure chargen services are not enabled
      block:
       - name: 2.1.1 Ensure chargen services are not enabled (chargen-dgram)
         stat:
            path: /etc/xinetd.d/chargen-dgram
         register: chargen_dgram_service
       - name: 2.1.1 Ensure chargen services are not enabled (chargen-dgram patch)
         service:
            name: chargen-dgram
            enabled: no
         notify: restart xinetd
         when: chargen_dgram_service.stat.exists
       - name: 2.1.1 Ensure chargen services are not enabled (chargen-stream)
         stat:
            path: /etc/xinetd.d/chargen-stream
         register: chargen_stream_service
       - name: 2.1.1 Ensure chargen services are not enabled (chargen-stream patch)
         service:
            name: chargen-stream
            enabled: no
         notify: restart xinetd
         when: chargen_stream_service.stat.exists

    - name: 2.1.2 Ensure daytime services are not enabled
      block:
      - name: 2.1.2 Ensure daytime services are not enabled (daytime-dgram)
        stat:
            path: /etc/xinetd.d/daytime-dgram
        register: daytime_dgram_service
      - name: 2.1.2 Ensure daytime services are not enabled (daytime-dgram patch)
        service:
            name: daytime-dgram
            enabled: no
        notify: restart xinetd
        when: daytime_dgram_service.stat.exists
      - name: 2.1.2 Ensure daytime services are not enabled (daytime-stream)
        stat:
            path: /etc/xinetd.d/daytime-stream
        register: daytime_stream_service
      - name: 2.1.2 Ensure daytime services are not enabled (daytime-stream)
        service:
            name: daytime-stream
            enabled: no
        notify: restart xinetd
        when: daytime_stream_service.stat.exists

    - name: 2.1.3 Ensure discard services are not enabled
      block:
       - name: 2.1.3 Ensure discard services are not enabled (discard-dgram)
         stat:
            path: /etc/xinetd.d/discard-dgram
         register: discard_dgram_service
       - name: 2.1.3 Ensure discard services are not enabled (discard-dgram patch)
         service:
            name: discard-dgram
            enabled: no
         notify: restart xinetd
         when: discard_dgram_service.stat.exists
       - name: 2.1.3 Ensure discard services are not enabled (discard-stream)
         stat:
            path: /etc/xinetd.d/discard-stream
         register: discard_stream_service
       - name: 2.1.3 Ensure discard services are not enabled (discard-stream patch)
         service:
            name: discard-stream
            enabled: no
         notify: restart xinetd
         when: discard_stream_service.stat.exists

    - name: 2.1.4 Ensure echo services are not enabled
      block:
      - name: 2.1.4 Ensure echo services are not enabled (echo-dgram)
        stat:
            path: /etc/xinetd.d/echo-dgram
        register: echo_dgram_service
      - name: 2.1.4 Ensure echo services are not enabled (echo-dgram patch)
        service:
            name: echo-dgram
            enabled: no
        notify: restart xinetd
        when: echo_dgram_service.stat.exists
      - name: 2.1.4 Ensure echo services are not enabled (echo-stream)
        stat:
            path: /etc/xinetd.d/echo-stream
        register: echo_stream_service
      - name: 2.1.4 Ensure echo services are not enabled (echo-stream patch)
        service:
            name: echo-stream
            enabled: no
        notify: restart xinetd
        when: echo_stream_service.stat.exists

    - name: 2.1.5 Ensure time services are not enabled
      block:
      - name: 2.1.5 Ensure time services are not enabled (time-dgram)
        stat:
            path: /etc/xinetd.d/time-dgram
        register: time_dgram_service
      - name: 2.1.5 Ensure time services are not enabled (time-dgram patch)
        service:
            name: time-dgram
            enabled: no
        notify: restart xinetd
        when: time_dgram_service.stat.exists
      - name: 2.1.5 Ensure time services are not enabled (time-stream)
        stat:
            path: /etc/xinetd.d/time-stream
        register: time_stream_service
      - name: 2.1.5 Ensure time services are not enabled (time-stream patch)
        service:
            name: time-stream
            enabled: no
        notify: restart xinetd
        when: time_stream_service.stat.exists

    - name: 2.1.6 Ensure rsh server is not enabled
      block:
      - name: 2.1.6 Ensure rsh server is not enabled (rsh)
        service:
          name: rsh.socket
          state: stopped
          enabled: false
        ignore_errors: true
      - name: 2.1.6 Ensure rsh server is not enabled (rlogin)
        service:
          name: rlogin.socket
          state: stopped
          enabled: false
        ignore_errors: true
      - name: 2.1.6 Ensure rsh server is not enabled (rexec)
        service:
          name: rexec.socket
          state: stopped
          enabled: false
        ignore_errors: true

    - name: 2.1.7 Ensure talk server is not enabled
      service:
        name: ntalk
        state: stopped
        enabled: false
      ignore_errors: true

    - name: 2.1.8 Ensure telnet server is not enabled
      service:
       name: telnet
       state: stopped
       enabled: false
      ignore_errors: true
  
    - name: 2.1.9 Ensure tftp server is not enabled
      block:
      - name: 2.1.9 Ensure tftp server is not enabled (Checking)
        stat:
            path: /etc/xinetd.d/tftp
        register: tftp_service
      - name: 2.1.9 Ensure tftp server is not enabled (Stopping)
        service:
            name: tftp
            state: stopped
            enabled: no
        notify: restart xinetd
        when: tftp_service.stat.exists
      ignore_errors: true

    - name: 2.1.10 Ensure xinetd is not enabled
      service:
       name: xinetd
       state: stopped
       enabled: false
      ignore_errors: true



 

